# Generated by Django 5.1.3 on 2024-12-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0003_remove_candidate_resume_url_candidate_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('issuing_country', models.CharField(max_length=100)),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='passports/')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='candidates.candidate')),
            ],
        ),
    ]
