# Generated by Django 5.1.3 on 2024-12-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_resume_url_candidate_resume'),
        ('passports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='candidates.candidate'),
        ),
    ]
