# Generated by Django 5.1.3 on 2024-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('SHORTLISTED', 'Shortlisted'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
    ]
