# Generated by Django 5.1.3 on 2024-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('REACHED_OUT', 'Reached Out'), ('RESPONDED', 'Responded'), ('NEW_APPLICATION', 'New Application'), ('RECRUITER_SCREEN', 'Recruiter Screen'), ('FIRST_INTERVIEW', '1st Interview'), ('SECOND_INTERVIEW', '2nd Interview'), ('REFERENCE_CHECK', 'Reference Check'), ('OFFER', 'Offer'), ('BACKGROUND_CHECK', 'Background Check'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('BAND', 'Band')], default='NEW_LEAD', max_length=20),
        ),
    ]
